name: Dotnet build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.1.x
      - run: dotnet test BinaryNotes.NET/BinaryNotes.sln /p:Version=0.0.0-latest
      - run: dotnet pack BinaryNotes.NET/BinaryNotes.sln -c Release /p:Version=0.0.0-latest
